// frontend-vue/src/components/Hero.vue
<template>
  <div class="hero min-h-screen bg-gradient-to-b from-primary/10 via-transparent to-transparent">
    <div class="block text-center justify-center hero-content">
      <div class="mb-5 flex justify-center">
         <SoundryLogo class="w-32 h-32 text-primary" />
      </div>
      <div>
        <h1 class="mb-1 text-6xl font-black text-base-content tracking-tight">Soundry</h1>
        <p class="mb-8 text-xl text-base-content/80 font-light">
          Universal Cloud Audio Downloader
        </p>
        
        <!-- Supported Platforms -->
        <div class="flex flex-wrap justify-center gap-4 mb-10 text-base-content/60">
           <div class="flex items-center gap-2 px-3 py-1 rounded-full bg-base-200/50 border border-base-content/10">
              <Icon icon="mdi:spotify" class="w-5 h-5" />
              <span class="text-sm font-medium">Spotify</span>
           </div>
           <div class="flex items-center gap-2 px-3 py-1 rounded-full bg-base-200/50 border border-base-content/10">
              <Icon icon="mdi:soundcloud" class="w-5 h-5" />
              <span class="text-sm font-medium">SoundCloud</span>
           </div>
           <div class="flex items-center gap-2 px-3 py-1 rounded-full bg-base-200/50 border border-base-content/10">
              <Icon icon="simple-icons:youtubemusic" class="w-5 h-5" />
              <span class="text-sm font-medium">YouTube Music</span>
           </div>
           <div class="flex items-center gap-2 px-3 py-1 rounded-full bg-base-200/50 border border-base-content/10">
              <span class="text-sm font-medium">+ Many More</span>
           </div>
        </div>
      </div>

      <SearchInput />
    </div>
  </div>
</template>

<script setup lang="ts">
import { Icon } from '@iconify/vue'
import SearchInput from '../components/SearchInput.vue'
import SoundryLogo from '../components/SoundryLogo.vue'

import { useBinaryThemeManager } from '../model/theme'
import { ref } from 'vue'

const themeMgr = useBinaryThemeManager({
  newLightAlias: 'soundry-light',
  newDarkAlias: 'soundry-dark',
})

const version = localStorage.getItem('version') || '0.0.0'
</script>

<style scoped>
.center {
  text-align: center;
  margin-left: auto;
  margin-right: auto;
}
</style>

// frontend/src/components/Hero.tsx
import { Icon } from '@iconify/react'
import SearchInput from './SearchInput'

const Hero = () => {
  return (
    <section className="hero">
      <div className="hero-icon">
        <Icon icon="clarity:music-note-line" />
      </div>
      <h1>Soundry</h1>
      <p className="hero-subtitle">Universal Cloud Audio Downloader</p>
      <div className="pills">
        <span className="pill">
          <Icon icon="mdi:spotify" /> Spotify
        </span>
        <span className="pill">
          <Icon icon="mdi:soundcloud" /> SoundCloud
        </span>
        <span className="pill">
          <Icon icon="simple-icons:youtubemusic" /> YouTube Music
        </span>
        <span className="pill">+ Many More</span>
      </div>
      <div style={{ width: '100%', marginTop: '1.5rem' }}>
        <SearchInput />
      </div>
    </section>
  )
}

export default Hero
