// frontend-vue/src/components/SearchInput.vue
<template>
  <div class="flex flex-row items-center w-full max-w-4xl mx-auto">
    <div class="join w-full shadow-lg">
       <!-- Format Selector -->
       <select v-model="sm.settings.value.format" class="select select-bordered join-item bg-base-100 focus:outline-none w-24">
          <option v-for="fmt in sm.settingsOptions.format" :key="fmt" :value="fmt">{{ fmt.toUpperCase() }}</option>
       </select>
       
       <!-- Input -->
      <input
        type="text"
        :placeholder="placeHolder"
        class="input input-bordered join-item w-full text-base-content bg-base-100 focus:outline-none text-lg px-6"
        v-model="searchManager.searchTerm.value"
        @keyup.enter="lookUp(searchManager.searchTerm.value)"
      />
      
      <!-- Action Button -->
      <button
        v-if="dm.loading.value"
        class="btn btn-square btn-primary join-item loading"
      ></button>
      <button
        v-else
        class="btn btn-square btn-primary join-item px-6 w-auto"
        @click="lookUp(searchManager.searchTerm.value)"
      >
        <span v-if="searchManager.isValidURL(searchManager.searchTerm.value)" class="font-bold mr-2">Download</span>
        <Icon
          v-if="searchManager.isValidURL(searchManager.searchTerm.value)"
          icon="clarity:download-line"
          class="h-6 w-6"
        />
        <Icon v-else icon="clarity:search-line" class="h-6 w-6" />
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onBeforeUnmount } from 'vue'
import { Icon } from '@iconify/vue'
import router from '../router'

import { useSearchManager } from '../model/search'
import { useDownloadManager } from '../model/download'
import { useSettingsManager } from '../model/settings'

const searchManager = useSearchManager()
const dm = useDownloadManager()
const sm = useSettingsManager()

const placeHolderOptions = [
  'Crossfire - Stephen',
  'https://open.spotify.com/track/4vfN00PlILRXy5dcXHQE9M?si=e4d9e7c044dd4a8f',
  'drugs - EDEN',
  'Não Gosto Eu Amo - Henrique e Juliano',
  'Perfect - Ed Sheeran',
  'Lightning Crashes - Live',
]

const placeHolder = ref(placeHolderOptions[0])

const polling = setInterval(() => {
  // Loop placeHolder value through placeHolderOptions by moving 0th index to end every 6 seconds
  placeHolderOptions.push(placeHolderOptions.shift()!)
  placeHolder.value = placeHolderOptions[0]
}, 6000)

onBeforeUnmount(() => {
  clearInterval(polling)
})

function lookUp(query) {
  if (searchManager.isValidURL(query)) {
    dm.fromURL(query)
    router.push({ name: 'Download' })
  } else if (searchManager.isValidSearch(query)) {
    let dest = { name: 'Search', params: { query: query } }
    if (searchManager.isValidSearch(query)) router.push(dest)
  } else {
    console.log('Invalid search term.')
  }
}
</script>

<style scoped></style>

// frontend/src/components/SearchInput.tsx
import { useEffect, useMemo, useState } from 'react'
import { Icon } from '@iconify/react'
import { useNavigate } from 'react-router-dom'
import { useSearchManager } from '../model/search'
import { useDownloadManager } from '../model/download'
import { useSettingsManager } from '../model/settings'

const placeholderOptions = [
  'Crossfire - Stephen',
  'https://open.spotify.com/track/4vfN00PlILRXy5dcXHQE9M?si=e4d9e7c044dd4a8f',
  'drugs - EDEN',
  'Nao Gosto Eu Amo - Henrique e Juliano',
  'Perfect - Ed Sheeran',
  'Lightning Crashes - Live',
]

const SearchInput = () => {
  const navigate = useNavigate()
  const searchManager = useSearchManager()
  const downloadManager = useDownloadManager()
  const settingsManager = useSettingsManager()
  const [placeholderIndex, setPlaceholderIndex] = useState(0)

  const placeholder = useMemo(
    () => placeholderOptions[placeholderIndex % placeholderOptions.length],
    [placeholderIndex]
  )

  useEffect(() => {
    const timer = setInterval(() => {
      setPlaceholderIndex((prev) => prev + 1)
    }, 6000)

    return () => clearInterval(timer)
  }, [])

  const lookUp = (query: string) => {
    if (searchManager.isValidURL(query)) {
      downloadManager.fromURL(query)
      navigate('/downloads')
    } else if (searchManager.isValidSearch(query)) {
      navigate(`/search/${encodeURIComponent(query)}`)
    }
  }

  return (
    <div style={{ width: '100%' }}>
      <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
        <select
          className="select"
          value={settingsManager.settings.format}
          onChange={(event) =>
            settingsManager.setSettings((prev) => ({
              ...prev,
              format: event.target.value,
            }))
          }
        >
          {settingsManager.settingsOptions.format.map((fmt) => (
            <option key={fmt} value={fmt}>
              {fmt.toUpperCase()}
            </option>
          ))}
        </select>
        <input
          className="input"
          type="text"
          placeholder={placeholder}
          value={searchManager.searchTerm}
          onChange={(event) => searchManager.setSearchTerm(event.target.value)}
          onKeyDown={(event) => {
            if (event.key === 'Enter') {
              lookUp(searchManager.searchTerm)
            }
          }}
        />
        <button
          className="btn btn-primary"
          type="button"
          onClick={() => lookUp(searchManager.searchTerm)}
          disabled={downloadManager.loading}
        >
          {searchManager.isValidURL(searchManager.searchTerm) ? 'Download' : 'Search'}
          <Icon
            icon={
              searchManager.isValidURL(searchManager.searchTerm)
                ? 'clarity:download-line'
                : 'clarity:search-line'
            }
            style={{ marginLeft: '0.5rem' }}
          />
        </button>
      </div>
    </div>
  )
}

export default SearchInput
