// frontend-vue/src/views/NotFound.vue
<template>
  <div class="min-h-screen bg-base-100 flex items-center justify-center px-6">
    <div class="text-center max-w-md">
      <h1 class="text-9xl font-bold text-base-content/10">404</h1>
      <h2 class="text-3xl font-bold mt-6 mb-4">Page Not Found</h2>
      <p class="text-base-content/60 mb-8">
        The page you're looking for doesn't exist or has been moved.
      </p>
      <router-link to="/" class="btn btn-primary">Go Home</router-link>
    </div>
  </div>
</template>

<script setup>
</script>

// frontend/src/pages/NotFound.tsx
import { Link } from 'react-router-dom'

const NotFound = () => {
  return (
    <div className="page" style={{ display: 'grid', placeItems: 'center' }}>
      <div style={{ textAlign: 'center', maxWidth: 480 }}>
        <h1 style={{ fontSize: '6rem', margin: 0, opacity: 0.2 }}>404</h1>
        <h2>Page Not Found</h2>
        <p style={{ color: 'var(--muted)' }}>
          The page you're looking for doesn't exist or has been moved.
        </p>
        <Link to="/" className="btn btn-primary">
          Go Home
        </Link>
      </div>
    </div>
  )
}

export default NotFound
