// frontend-vue/src/views/Terms.vue
<template>
  <div class="min-h-screen bg-base-100 py-20 px-6">
    <div class="max-w-3xl mx-auto">
      
      <div class="mb-20">
        <h1 class="text-6xl font-bold mb-6 tracking-tight">Terms of Service</h1>
        <p class="text-sm text-base-content/40">Last updated: December 17, 2025</p>
      </div>

      <div class="prose prose-lg max-w-none">
        
        <h2 class="text-3xl font-bold mt-16 mb-6">Acceptance of Terms</h2>
        <p class="text-base-content/80 leading-relaxed">
          By using Soundry, you agree to these terms. Soundry is provided "as-is" without any warranties.
        </p>

        <h2 class="text-3xl font-bold mt-16 mb-6">License</h2>
        <p class="text-base-content/80 leading-relaxed">
          Soundry is open-source software licensed under the MIT License. You are free to use, modify, and distribute the software in accordance with the license terms.
        </p>

        <h2 class="text-3xl font-bold mt-16 mb-6">Proper Use</h2>
        <p class="text-base-content/80 leading-relaxed mb-4">
          Soundry is intended for personal, educational, and archival purposes. You agree to:
        </p>
        <ul class="space-y-2 text-base-content/80">
          <li>Respect copyright laws in your jurisdiction</li>
          <li>Support artists by purchasing music when possible</li>
          <li>Use the software responsibly and ethically</li>
          <li>Not use the software for commercial redistribution</li>
        </ul>

        <h2 class="text-3xl font-bold mt-16 mb-6">Disclaimer of Liability</h2>
        <p class="text-base-content/80 leading-relaxed">
          The developers of Soundry are not responsible for how you use the software. You assume all risks and legal responsibilities for your usage.
        </p>

        <h2 class="text-3xl font-bold mt-16 mb-6">Changes to Terms</h2>
        <p class="text-base-content/80 leading-relaxed">
          We may update these terms from time to time. Continued use of Soundry constitutes acceptance of updated terms.
        </p>

        <div class="mt-12">
          <router-link to="/" class="btn btn-ghost">Back to Home</router-link>
        </div>

      </div>
    </div>
  </div>
</template>

<script setup>
</script>

// frontend/src/pages/Terms.tsx
import { Link } from 'react-router-dom'

const Terms = () => {
  return (
    <div className="page">
      <div className="container">
        <div style={{ marginBottom: '3rem' }}>
          <h1>Terms of Service</h1>
          <p style={{ color: 'var(--muted)' }}>Last updated: December 17, 2025</p>
        </div>
        <div style={{ display: 'grid', gap: '1.5rem' }}>
          <section>
            <h2>Acceptance of Terms</h2>
            <p>
              By using Soundry, you agree to these terms. Soundry is provided "as-is" without any
              warranties.
            </p>
          </section>
          <section>
            <h2>License</h2>
            <p>
              Soundry is open-source software licensed under the MIT License. You are free to use,
              modify, and distribute the software in accordance with the license terms.
            </p>
          </section>
          <section>
            <h2>Proper Use</h2>
            <p>Soundry is intended for personal, educational, and archival purposes. You agree to:</p>
            <ul>
              <li>Respect copyright laws in your jurisdiction</li>
              <li>Support artists by purchasing music when possible</li>
              <li>Use the software responsibly and ethically</li>
              <li>Not use the software for commercial redistribution</li>
            </ul>
          </section>
          <section>
            <h2>Disclaimer of Liability</h2>
            <p>
              The developers of Soundry are not responsible for how you use the software. You assume all
              risks and legal responsibilities for your usage.
            </p>
          </section>
          <section>
            <h2>Changes to Terms</h2>
            <p>
              We may update these terms from time to time. Continued use of Soundry constitutes
              acceptance of updated terms.
            </p>
          </section>
          <div>
            <Link to="/" className="btn btn-ghost">
              Back to Home
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Terms
